# Generated by Django 4.0.6 on 2022-07-20 03:42

from django.db import migrations, models
from django.utils.text import slugify


def add_slug(apps, schema_editor):
    BookTest = apps.get_model('tests', 'BookTest')
    for book in BookTest.objects.all():
        book.slug = slugify(book.title)
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_booktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktest',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(add_slug)
    ]
