# Generated by Django 4.0.6 on 2022-07-20 07:12

from django.db import migrations
from django.utils.text import slugify


def add_slug(apps, schema_editor):
    BookTest = apps.get_model('tests', 'BookTest')
    for book in BookTest.objects.all():
        book.slug = slugify(book.title)
        book.save()

def remove_slug(apps, schema_editor):
    BookTest = apps.get_model('tests', 'BookTest')
    for book in BookTest.objects.all():
        book.slug = None
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_booktest_slug'),
    ]

    operations = [
        migrations.RunPython(add_slug, remove_slug)
    ]
