# Generated by Django 4.0.6 on 2022-07-20 07:15

from django.db import migrations, models

from django.utils.text import slugify


def add_slug1(apps, schema_editor):
    BookTest = apps.get_model('tests', 'BookTest')
    for book in BookTest.objects.all():
        book.slug1 = slugify(book.title)
        book.save()

def remove_slug1(apps, schema_editor):
    BookTest = apps.get_model('tests', 'BookTest')
    for book in BookTest.objects.all():
        book.slug1 = None
        book.save()
class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20220720_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktest',
            name='slug1',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(add_slug1, remove_slug1)
    ]
