# Generated by Django 4.0.6 on 2022-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_run_migrate', '0003_service_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
