# Generated by Django 4.0.6 on 2022-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_run_migrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='service_categories',
            field=models.ManyToManyField(default=None, null=True, related_name='service_categories_business', to='test_run_migrate.servicecategory'),
        ),
    ]
