# Generated by Django 4.0.6 on 2022-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_run_migrate', '0002_business_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
