# Generated by Django 4.0.6 on 2022-07-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('duration', models.DateTimeField()),
            ],
        ),
    ]
